### ISSUE TITLE
Repo name change / packagist

### ISSUE THREAD

**Issue by lucasmichot** [borisrepl/boris#100]
Hello, since the recent change of name of the repo (`d11wtq/boris` to `borisrepl/boris`), the packagist reference still points to `https://github.com/d11wtq/boris.git`.

Unless some composer cache exists on the server or on the local machine for `d11wtq/boris` package, it is now impossible to get it via `composer`, unless we had a specific `repositories` section in the `composer.json` file.

```sh
*** [err :: u10657@worker02.addapp.skyscrape.rs] - Installing d11wtq/boris (v1.0.8)
*** [err :: u10657@worker02.addapp.skyscrape.rs] Downloading
*** [err :: u10657@worker02.addapp.skyscrape.rs] Failed to download d11wtq/boris from dist: The "https://api.github.com/repos/d11wtq/boris/zipball/125dd4e5752639af7678a22ea597115646d89c6e" file could not be downloaded (HTTP/1.1 404 Not Found)
```

Can you refresh or update the package reference in `https://packagist.org` so that it now points to `https://github.com/d11wtq/boris.git` ?

**Comment by GrahamCampbell** [comment]
:+1: it needs to point to `https://github.com/borisrepl/boris.git`.

**Comment by lucasmichot** [comment]
Yes, messes with the final repo.
Thx @GrahamCampbell

**Comment by d11wtq** [comment]
This must be a caching issue. The source in packagist is already set correctly.
![screen shot 2015-03-11 at 9 49 45 am](https://cloud.githubusercontent.com/assets/37948/6587105/1988b72e-c7d4-11e4-87b5-c19766b7202f.png)

See also earlier issue: https://github.com/borisrepl/boris/issues/99

**Comment by GrahamCampbell** [comment]
Yeh, composer's cache is total bull shit. It really annoys me how broken it is. It caches branch aliases wrong too.

**Comment by tejasmanohar** [comment]
@d11wtq Yeah, it's caching...

**Comment by anthonyvanbeek** [comment]
@d11wtq please help, I'm getting this in my eb-commandprocessor.log when trying to deploy my app to AWS Elastic Beantstalk. (It's a laravel 4.2 app)

```
 - Installing d11wtq/boris (v1.0.8)
    Downloading: connection...

  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/d11wtq/boris/zipball/125dd4e5752639af7678a22ea597115646d89c6e" file could not be downloaded (HTTP/1.1 404 Not Found)
```

I've tried the additions to my composer.json file but it didn't make a difference.

Many thanks,

**Comment by GrahamCampbell** [comment]
> please help, I'm getting this in my eb-commandprocessor.log when trying to deploy my app to AWS Elastic Beanstalk. (It's a laravel 4.2 app)

You need to make sure your lock file is updated, and your composer cache is cleared.
