### ISSUE TITLE
Broken backwards compatibility

### ISSUE THREAD

**Issue by Gisleburt** [borisrepl/boris#103]
It's probably too late to fix this but Version 1.0.9 breaks backwards compatibility by relying on additional dependencies:

    ext-readline: *
    ext-pcntl: *
    ext-posix: *

The result of this (when combined with other work I was doing) was that it took down part of my website for almost an hour while I diagnosed the problem and fixed my composer.json to point directly to 1.0.8. Considering the release notes for 1.0.9 and 1.0.10 are "old array syntax" and "team bullets" I'm not sure why these extra dependencies are required

However, to follow Semantic Versioning, the version number should have bumped to 2.0.0.

**Comment by GrahamCampbell** [comment]
> However, to follow Semantic Versioning, the version number should have bumped to 2.0.0.

Not true. Boris has depended on these since 1.0.0, they were just forgotten from the composer.json.

**Comment by Gisleburt** [comment]
I don't know what to say to that other than, my app worked, then it didn't because I don't have `ext-posix` installed. Perhaps this is a problem with Laravel listing it as a dependency but not actually using it.

**Comment by GrahamCampbell** [comment]
It was a bug that your app was installable before.

**Comment by GrahamCampbell** [comment]
>  Perhaps this is a problem with Laravel listing it as a dependency but not actually using it.

Nope, it was a problem with boris.

**Comment by GrahamCampbell** [comment]
We've ditched boris in L5 anyway, so you'll no longer be affected by this if you upgrade.

**Comment by bobthecow** [comment]
@GrahamCampbell what would it take to convince the powers that be to release a patch version that moves boris to suggested in L4? It'd save a lot of issues on this repo, at the very least.

**Comment by GrahamCampbell** [comment]
@bobthecow It was decided ages ago that we're not going to do anything about it. It's not our fault if people don't know what they're doing unfortunately. Removing the dependency would be a large BC break, and restricting the version used would prevent people with the extensions from getting bug fixes. We're between a rock and a hard place.

**Comment by bobthecow** [comment]
Hey, I understand. It's not my fight; I'm not using L4 at all. I just think there's got to be a better way for the users. They're between a rock and a hard place and you ;)

**Comment by GrahamCampbell** [comment]
@bobthecow People affected by this can manually restrict the boris version if they so choose. That aside, we do not support Laravel 4 anymore, anyway.

**Comment by Gisleburt** [comment]
That's been my temporary fix too:

    "d11wtq/boris": "1.0.8"

This obviously won't help you if you actually are using Boris though, as you will need those dependencies. In the long term I'm removing Laravel from this project anyway so the problem should resolve itself. 

Not sure what the best way to help other people is though, unless you regress those changes and bump the major version number as originally suggested. It may not be specifically correct, but it seems to be the path of least friction that doesn't leave people in the same trouble as me, only discovering its broken in a live environment after other major changes.

**Comment by tejasmanohar** [comment]
We've always had the dependency and are no longer in L4.
