### ISSUE TITLE
Previous and next command with up and down arrow not working

### ISSUE THREAD

**Issue by msankhala** [borisrepl/boris#104]
Sorry to create this issue if this feature is already in boris. I am using laravel tinker command which uses boris as REPL. When i use the "up" and "down" key to goto previous and next command it show key code like " ^[[A^[[C^[[B^[[D  ". How can i fix this. I am using bash on mac.

![screen shot 2015-04-21 at 11 22 39 am](https://cloud.githubusercontent.com/assets/234241/7246331/4747845a-e819-11e4-85e0-1ba55fc42de3.png)

**Comment by GrahamCampbell** [comment]
This is the wrong repo! Look at the first line out of output. It doesn't say boris...

**Comment by GrahamCampbell** [comment]
> I am using laravel tinker command which uses boris as REPL

No it doesn't. :)

**Comment by tejasmanohar** [comment]
Used to but no longer.

**Comment by bobthecow** [comment]
@msankhala feel free to open an issue at @bobthecow/psysh … but likely your issue is that you're using PHP without readline or libedit support.

**Comment by msankhala** [comment]
Thanks you for giving me required information.

**Comment by msankhala** [comment]
@bobthecow Between readline and libedit which one is better? How can i decide between these two? Here http://php.find-info.ru/php/013/LiB0149.html it say "PHP uses this libedit, rather than readline itself, due to license issues."

**Comment by bobthecow** [comment]
@msankhala This issue isn't really the place for support for PsySH. Please open an issue there.
