### ISSUE TITLE
 Undefined variable: boris in .borisrc

### ISSUE THREAD

**Issue by kmungai** [borisrepl/boris#113]
The `$boris` variable is no longer exposed to the configuration files as documented [here](https://github.com/borisrepl/boris/wiki/Using-start-hooks#user-configuration-files)

Edit
-
Might be caused by commits 71843a506a867372fa27eae317af5197fdff2658 and 819a3c2a8a12bc0369da9f4ac8c30c2c1367574b

**Comment by tejasmanohar** [comment]
Solved by @sserbin
