### ISSUE TITLE
CURL Issue

### ISSUE THREAD

**Issue by GrahamCampbell** [borisrepl/boris#66]
Curl becomes broken in Boris after one use. See https://github.com/dropbox/dropbox-sdk-php/issues/12.

**Comment by tejasmanohar** [comment]
@GrahamCampbell still facing issue? This is something we have to look more into for sure.

**Comment by GrahamCampbell** [comment]
I no longer user boris, sorry. I switched to psysh.

**Comment by GrahamCampbell** [comment]
So has laravel. We had to do to the addition of the extension requirements in your composer.json. We used to just silently callback to something else on laravel for windows, but now we can't install our dependencies.

**Comment by bobthecow** [comment]
FWIW PsySH has the same issue when using the forking loop. It seems to be curl+fork(+php?) stupidness, and I haven't been able to come up with a workaround, other than disabling pcntl support :-/

**Comment by tejasmanohar** [comment]
@bobthecow I've noticed the same thing. Not sure what to do about this honestly.
