### ISSUE TITLE
Composer can't find the package on github

### ISSUE THREAD

**Issue by EloProf** [borisrepl/boris#98]
Composer looks for the `dist` version of the package in the wrong place:
```
[Composer\Downloader\TransportException]
The "https://api.github.com/repos/d11wtq/boris/zipball/31055b15e2d3fe47f31f6aa8e277f8f3fc7eb483" file could not be downloaded (HTTP/1.1 404 Not Found)
```

**Comment by tejasmanohar** [comment]
@EloProf This repo has been migrated. See new URL. I just updated the Wiki w/ this information as well. Sad that Composer doesn't follow redirects :cry:

**Comment by dsnoeck** [comment]
Don't you need also to update link on packagist.org ?

**Comment by dhotson** [comment]
@d11wtq may need to update the package on packagist? https://packagist.org/packages/d11wtq/boris
Also, maybe update the https://github.com/borisrepl/boris/blob/master/composer.json file?

**Comment by ronanguilloux** [comment]
@dhotson +1

**Comment by dhotson** [comment]
Maybe might just need to take some care to make sure old composer references continue to work.

**Comment by carlosafonso** [comment]
@dsnoeck +1 on the packagist link update.

We are having trouble with our Laravel 4-based apps since its the framework who has the dependency.

**Comment by namelivia** [comment]
@carlosafonso +1 I'm also experiencing failed tests on my Laravel4 apps because of this.

**Comment by EloProf** [comment]
@tejasmanohar I had another packages face the same problem some time ago but the package maintainer was able to apply a change that fixed it. I don't know for sure but as @dhotson mentioned the fix was probably made on packagist, which would probably make this the resposibility of @d11wtq

**Comment by tejasmanohar** [comment]
My apologies. Yes, just tested with a dummy app, and indeed - @d11wtq needs both update the packagist link (+ composer.json but only makes sense to do this at the same time). I reached out to him via Twitter DM as well as we tagged him quite a few times here on the GitHub repo, so hopefully this is done shortly.

**Comment by codeslaw** [comment]
@d11wtq Major deployments waiting to deploy, please update packagist :)

**Comment by d11wtq** [comment]
I updated packagist earlier, so all the URLs are now correct. Not sure why it's still happening, but guessing some sort of caching. Unfortunately I'm on vacation in the mountains and only have my cell phone with me, but perhaps it will work if a new version gets released?

**Comment by d11wtq** [comment]
Update via Twitter: apparently it's working now :)

**Comment by kimoi** [comment]
All good here now. Thanks.

**Comment by tejasmanohar** [comment]
Same here :tada:

**Comment by benjaminkohl** [comment]
I don't know why, but I am experiencing the problem again. In my composer lock file, it looks like it is still trying to pull the repo from the old location. I have cleared my composer cache so I am not sure what else to do. I got this working at the end of last week so I am not sure why the issue is resurfacing. Any ideas?

**Comment by tejasmanohar** [comment]
>You need to make sure your lock file is updated, and your composer cache is cleared.
-- @GrahamCampbell

https://github.com/borisrepl/boris/issues/100#issuecomment-78343519

**Comment by benjaminkohl** [comment]
Yeah, I've cleared the composer cache at least ten times locally and on the live server. And I keep running composer update over and over hoping it will just all of a sudden update the lock file with the correct changes. No luck.
