### ISSUE TITLE
Composer link via packagist (d11wtq/boris) does not successfully resolve to new borisrepl/boris

### ISSUE THREAD

**Issue by Lidbetter** [borisrepl/boris#99]
Using this package due to laravel dependence, as far as I can tell I cannot alias this git to d11wtq/bori

Does not work:
https://api.github.com/repos/d11wtq/boris/zipball/31055b15e2d3fe47f31f6aa8e277f8f3fc7eb483

Will resolve to new link (borisrepl/boris):
https://github.com/d11wtq/boris/zipball/31055b15e2d3fe47f31f6aa8e277f8f3fc7eb483

Composer error message:

    - Installing d11wtq/boris (v1.0.10)
           Downloading: connection...
           Failed to download d11wtq/boris from dist: The "https://api.github.com/repos/d11wtq/boris/zipball/31055b15e2d3fe47f31f6aa8e277f8f3fc7eb483" file could not be downloaded (HTTP/1.1 404 Not Found)
           Now trying to download from source
         - Installing d11wtq/boris (v1.0.10)
           Cloning 31055b15e2d3fe47f31f6aa8e277f8f3fc7eb483
       
       
                                                                                                   
         [RuntimeException]                                                                        
         Failed to clone git@github.com:d11wtq/boris.git via git, https, ssh protocols, aborting.  
         - git://github.com/d11wtq/boris.git                                                       
           Cloning into '/tmp/build_ae947ef6a7fe49c44b08f7c7d2f5c3e2/vendor/d11wtq/boris'...       
           fatal: Not a git repository: '.'                                                        
         - https://github.com/d11wtq/boris.git                                                     
           Cloning into '/tmp/build_ae947ef6a7fe49c44b08f7c7d2f5c3e2/vendor/d11wtq/boris'...       
           fatal: Not a git repository: '.'                                                        
         - git@github.com:d11wtq/boris.git                                                         
           Cloning into '/tmp/build_ae947ef6a7fe49c44b08f7c7d2f5c3e2/vendor/d11wtq/boris'...       
           Host key verification failed.                                                           
           fatal: Could not read from remote repository.                                           
                                                                                                   
           Please make sure you have the correct access rights                                     
           and the repository exists.

**Comment by Lidbetter** [comment]
Temporary workaround here:

https://github.com/borisrepl/boris/issues/97#issuecomment-77574714

**Comment by tejasmanohar** [comment]
Same source of error as #98
